import io
import logging
from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from config import OUTPUT_DIR, MAX_BULLETS_PER_SLIDE

logger = logging.getLogger(__name__)

SLIDE_WIDTH = Inches(13.333)
SLIDE_HEIGHT = Inches(7.5)
TITLE_FONT_SIZE = Pt(36)
BULLET_FONT_SIZE = Pt(18)
ACCENT_COLOR = RGBColor(0x1A, 0x56, 0xDB)
DARK_BG = RGBColor(0x1E, 0x1E, 0x2E)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
LIGHT_GRAY = RGBColor(0xCC, 0xCC, 0xCC)


def set_slide_bg(slide, color):
    background = slide.background
    fill = background.fill
    fill.solid()
    fill.fore_color.rgb = color


def add_textbox(slide, left, top, width, height, text, font_size, color=WHITE, bold=False, align=PP_ALIGN.LEFT):
    txBox = slide.shapes.add_textbox(left, top, width, height)
    tf = txBox.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.text = text
    p.font.size = font_size
    p.font.color.rgb = color
    p.font.bold = bold
    p.alignment = align
    return tf


def add_bullet_textbox(slide, left, top, width, height, items, font_size=BULLET_FONT_SIZE, color=LIGHT_GRAY):
    txBox = slide.shapes.add_textbox(left, top, width, height)
    tf = txBox.text_frame
    tf.word_wrap = True
    for i, item in enumerate(items[:MAX_BULLETS_PER_SLIDE]):
        if i == 0:
            p = tf.paragraphs[0]
        else:
            p = tf.add_paragraph()
        p.text = f"  {item}"
        p.font.size = font_size
        p.font.color.rgb = color
        p.space_after = Pt(8)
        p.level = 0
    return tf


def add_accent_line(slide, left, top, width):
    shape = slide.shapes.add_shape(
        1, left, top, width, Pt(4)
    )
    shape.fill.solid()
    shape.fill.fore_color.rgb = ACCENT_COLOR
    shape.line.fill.background()
    return shape


def add_image_to_slide(slide, image_bytes, left, top, width, height):
    try:
        image_stream = io.BytesIO(image_bytes)
        slide.shapes.add_picture(image_stream, left, top, width, height)
        return True
    except Exception as e:
        logger.error(f"Failed to add image: {e}")
        return False


def add_title_slide(prs, title: str):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    set_slide_bg(slide, DARK_BG)
    add_accent_line(slide, Inches(1), Inches(2.8), Inches(11.333))
    add_textbox(
        slide, Inches(1), Inches(1.5), Inches(11.333), Inches(1.5),
        title, Pt(44), WHITE, bold=True, align=PP_ALIGN.LEFT
    )
    add_textbox(
        slide, Inches(1), Inches(3.2), Inches(11.333), Inches(0.8),
        "Generated by AI Presentation Maker", Pt(20), LIGHT_GRAY, align=PP_ALIGN.LEFT
    )


def add_content_slide(prs, heading: str, bullets: list[str], image_bytes: bytes | None = None):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    set_slide_bg(slide, DARK_BG)
    add_accent_line(slide, Inches(0.8), Inches(0.9), Inches(4))
    add_textbox(
        slide, Inches(0.8), Inches(0.2), Inches(11.733), Inches(0.9),
        heading, TITLE_FONT_SIZE, WHITE, bold=True
    )
    if image_bytes:
        add_image_to_slide(slide, image_bytes, Inches(7.5), Inches(1.5), Inches(5), Inches(5.2))
        add_bullet_textbox(
            slide, Inches(0.8), Inches(1.5), Inches(6.2), Inches(5.5),
            bullets, BULLET_FONT_SIZE, LIGHT_GRAY
        )
    else:
        add_bullet_textbox(
            slide, Inches(0.8), Inches(1.5), Inches(11.733), Inches(5.5),
            bullets, BULLET_FONT_SIZE, LIGHT_GRAY
        )


async def generate_pptx(title: str, slides_data: list[dict]) -> bytes:
    prs = Presentation()
    prs.slide_width = SLIDE_WIDTH
    prs.slide_height = SLIDE_HEIGHT
    add_title_slide(prs, title)
    for slide in slides_data:
        add_content_slide(
            prs,
            slide.get("heading", ""),
            slide.get("bullets", []),
            slide.get("image_bytes")
        )
    buf = io.BytesIO()
    prs.save(buf)
    buf.seek(0)
    return buf.getvalue()
